# Basic information
title: "Mizu no oto"
tagline: 'A blog about code, litterature and other miscellaneous shenanigans.'
url: 'https://yomguithereal.github.io'
baseurl: ''

# Owner/author information
owner:
  name: Guillaume Plique
  twitter: Yomguithereal
  github: Yomguithereal
  disqus: mizunooto

highlighter: pygments
markdown: redcarpet
